name: "release"
  
on: push

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: lint
        uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install charmcraft
        run: |
          pip install charmcraft

      - name: Build charms
        run: |
          for charm in slurmd slurmdbd slurmctld slurmrestd; do
              charmcraft build --from charm-$charm/
          done
       
       

